/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Parking_lot;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author HARPREET
 */
public class Car extends javax.swing.JFrame {
     int x=200;
     int y=600;
     
    /**
     * Creates new form Bike
     */
    public Car() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        beigep = new javax.swing.JPanel();
        menu1 = new javax.swing.JLabel();
        brownp = new javax.swing.JPanel();
        menu2 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        records = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        phlbl = new javax.swing.JLabel();
        vnolbl = new javax.swing.JLabel();
        entrylbl = new javax.swing.JLabel();
        exitlbl = new javax.swing.JLabel();
        owner = new javax.swing.JTextField();
        phnno = new javax.swing.JTextField();
        vehicleno = new javax.swing.JTextField();
        hr1 = new javax.swing.JSpinner();
        min1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        am1 = new javax.swing.JComboBox();
        hr2 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        min2 = new javax.swing.JSpinner();
        am2 = new javax.swing.JComboBox();
        entrydatelbl = new javax.swing.JLabel();
        entrydate1 = new javax.swing.JTextField();
        exitdatelbl = new javax.swing.JLabel();
        exitdate1 = new javax.swing.JTextField();
        cal = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 211, 163));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel1.setFont(new java.awt.Font("Niagara Engraved", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 0));
        jLabel1.setText("       4-WHEELER");

        jLayeredPane2.setBackground(new java.awt.Color(255, 255, 255));

        beigep.setBackground(new java.awt.Color(255, 211, 163));

        menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Parking_lot/menu.png"))); // NOI18N
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout beigepLayout = new javax.swing.GroupLayout(beigep);
        beigep.setLayout(beigepLayout);
        beigepLayout.setHorizontalGroup(
            beigepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beigepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        beigepLayout.setVerticalGroup(
            beigepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beigepLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        brownp.setBackground(new java.awt.Color(153, 102, 0));

        menu2.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        menu2.setForeground(new java.awt.Color(255, 211, 163));
        menu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu2.setText("YOUR PARKING");
        menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu2MouseClicked(evt);
            }
        });

        home.setFont(new java.awt.Font("Segoe UI Light", 1, 15)); // NOI18N
        home.setForeground(new java.awt.Color(255, 211, 163));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("HOME");
        home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 211, 163), 2, true));

        records.setFont(new java.awt.Font("Segoe UI Light", 1, 15)); // NOI18N
        records.setForeground(new java.awt.Color(255, 211, 163));
        records.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        records.setText("RECORDS");
        records.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 211, 163), 2, true));

        logout.setFont(new java.awt.Font("Segoe UI Light", 1, 15)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 211, 163));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("LOG OUT");
        logout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 211, 163), 2, true));

        contact.setFont(new java.awt.Font("Segoe UI Light", 1, 15)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 211, 163));
        contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contact.setText("CONTACT US");
        contact.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 211, 163), 2, true));

        javax.swing.GroupLayout brownpLayout = new javax.swing.GroupLayout(brownp);
        brownp.setLayout(brownpLayout);
        brownpLayout.setHorizontalGroup(
            brownpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brownpLayout.createSequentialGroup()
                .addGroup(brownpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(brownpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(brownpLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(brownpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(records, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(home, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addContainerGap())
        );
        brownpLayout.setVerticalGroup(
            brownpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brownpLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(records, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(beigep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(brownp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(beigep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(brownp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2.setLayer(beigep, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(brownp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        namelbl.setBackground(new java.awt.Color(255, 255, 255));
        namelbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        namelbl.setForeground(new java.awt.Color(153, 102, 0));
        namelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namelbl.setText("OWNER'S NAME");
        namelbl.setPreferredSize(new java.awt.Dimension(200, 30));

        phlbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        phlbl.setForeground(new java.awt.Color(153, 102, 0));
        phlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phlbl.setText("OWNER'S CONTACT NO.");
        phlbl.setPreferredSize(new java.awt.Dimension(200, 30));

        vnolbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        vnolbl.setForeground(new java.awt.Color(153, 102, 0));
        vnolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vnolbl.setText("VEHICLE NO.");
        vnolbl.setPreferredSize(new java.awt.Dimension(200, 30));

        entrylbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        entrylbl.setForeground(new java.awt.Color(153, 102, 0));
        entrylbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrylbl.setText("ENTRY TIME");

        exitlbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        exitlbl.setForeground(new java.awt.Color(153, 102, 0));
        exitlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitlbl.setText("EXIT TIME");
        exitlbl.setPreferredSize(new java.awt.Dimension(200, 30));

        owner.setBackground(new java.awt.Color(255, 211, 163));
        owner.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        owner.setForeground(new java.awt.Color(153, 102, 0));
        owner.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        owner.setBorder(null);
        owner.setPreferredSize(new java.awt.Dimension(200, 30));

        phnno.setBackground(new java.awt.Color(255, 211, 163));
        phnno.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        phnno.setForeground(new java.awt.Color(153, 102, 0));
        phnno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phnno.setBorder(null);
        phnno.setPreferredSize(new java.awt.Dimension(200, 30));

        vehicleno.setBackground(new java.awt.Color(255, 211, 163));
        vehicleno.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        vehicleno.setForeground(new java.awt.Color(153, 102, 0));
        vehicleno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vehicleno.setBorder(null);
        vehicleno.setPreferredSize(new java.awt.Dimension(200, 30));

        hr1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));
        hr1.setPreferredSize(new java.awt.Dimension(40, 30));

        min1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        min1.setPreferredSize(new java.awt.Dimension(40, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(":");

        am1.setBackground(new java.awt.Color(255, 211, 163));
        am1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "PM" }));
        am1.setPreferredSize(new java.awt.Dimension(50, 30));

        hr2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));
        hr2.setPreferredSize(new java.awt.Dimension(40, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(":");

        min2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        min2.setPreferredSize(new java.awt.Dimension(40, 30));

        am2.setBackground(new java.awt.Color(255, 211, 163));
        am2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "PM" }));
        am2.setPreferredSize(new java.awt.Dimension(50, 30));

        entrydatelbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        entrydatelbl.setForeground(new java.awt.Color(153, 102, 0));
        entrydatelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrydatelbl.setText("ENTRY DATE");
        entrydatelbl.setPreferredSize(new java.awt.Dimension(200, 30));

        entrydate1.setBackground(new java.awt.Color(255, 211, 163));
        entrydate1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        entrydate1.setForeground(new java.awt.Color(153, 102, 0));
        entrydate1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entrydate1.setBorder(null);
        entrydate1.setPreferredSize(new java.awt.Dimension(200, 30));

        exitdatelbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        exitdatelbl.setForeground(new java.awt.Color(153, 102, 0));
        exitdatelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitdatelbl.setText("EXIT DATE");
        exitdatelbl.setPreferredSize(new java.awt.Dimension(200, 30));

        exitdate1.setBackground(new java.awt.Color(255, 211, 163));
        exitdate1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        exitdate1.setForeground(new java.awt.Color(153, 102, 0));
        exitdate1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        exitdate1.setBorder(null);
        exitdate1.setPreferredSize(new java.awt.Dimension(200, 30));

        cal.setBackground(new java.awt.Color(153, 102, 0));
        cal.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        cal.setForeground(new java.awt.Color(255, 211, 163));
        cal.setText("CALCULATE FEES");
        cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(153, 102, 0));
        jSeparator1.setForeground(new java.awt.Color(153, 102, 0));

        jSeparator2.setBackground(new java.awt.Color(153, 102, 0));
        jSeparator2.setForeground(new java.awt.Color(153, 102, 0));

        jSeparator3.setBackground(new java.awt.Color(153, 102, 0));
        jSeparator3.setForeground(new java.awt.Color(153, 102, 0));

        jSeparator4.setBackground(new java.awt.Color(153, 102, 0));
        jSeparator4.setForeground(new java.awt.Color(153, 102, 0));

        jSeparator5.setBackground(new java.awt.Color(153, 102, 0));
        jSeparator5.setForeground(new java.awt.Color(153, 102, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 75, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(phlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(entrylbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(exitlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exitdatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vnolbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entrydatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(owner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vehicleno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(hr2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(min2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(am2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(exitdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entrydate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(hr1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(min1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(am1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(cal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(owner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phlbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vnolbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entrydatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entrydate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entrylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hr1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(am1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitdatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(cal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exitlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hr2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(min2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(am2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 34, Short.MAX_VALUE))
            .addComponent(jLayeredPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseClicked
        if(x==200){
            beigep.setSize(x,y);
            Thread t= new Thread(){
               @Override
               public void run(){
                   try{
                      for(int i=200;i>=0;i--){
                          Thread.sleep(1);
                          beigep.setSize(i,y);
                      } 
                   }
                   catch(Exception e){
                       e.printStackTrace();
                   }
               }
            };t.start();
            x=0;
        }
// TODO add your handling code here:
    }//GEN-LAST:event_menu1MouseClicked

    private void menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2MouseClicked
        
        if(x==0){
            beigep.show();
            beigep.setSize(x,y);
            Thread t=new Thread(){
                @Override
                public void run(){
                    try{
                       for(int i=0;i<=x;i++){
                          Thread.sleep(1);
                          beigep.setSize(i,y); 
                       }
                    }
                    catch(Exception e){
                        e.printStackTrace();
                    }
                }
            };t.start();
            x=200;
        }
// TODO add your handling code here:
    }//GEN-LAST:event_menu2MouseClicked
    private Date date_time(int hour, int min, String ampm){
      String timeStr = String.format("%d:%02d %s", hour, min, ampm);
    SimpleDateFormat format = new SimpleDateFormat("hh:mm a");
    Date date = null;
    try {
        date = format.parse(timeStr);
    } catch (ParseException ex) {
    }
    return date;
        
        
    }
    
    private Date parseDateTime(String dateStr, String timeStr, String amPmStr) throws ParseException {
      SimpleDateFormat inputDateFormat = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat outputDateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date date = inputDateFormat.parse(dateStr);
    String formattedDateStr = outputDateFormat.format(date);

    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm a");
    String dateTimeStr = formattedDateStr + " " + timeStr + " " + amPmStr;
    return dateFormat.parse(dateTimeStr);
}
    
    
    private void calActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calActionPerformed
         try {
             int hourly= 50;
             int daily= 150;
             String contact= phnno.getText();
             String name= owner.getText();
             String vehicle= vehicleno.getText();
             String entryDateStr = entrydate1.getText();
             String entryTimeStr = String.format("%02d:%02d", (int)hr1.getValue(), (int)min1.getValue());
             String entryAmPmStr = am1.getSelectedItem().toString();
             String exitDateStr = exitdate1.getText();
             String exitTimeStr = String.format("%02d:%02d", (int)hr2.getValue(), (int)min2.getValue());
             String exitAmPmStr = am2.getSelectedItem().toString();
             
              Date entryDateTime = parseDateTime(entryDateStr, entryTimeStr, entryAmPmStr);
              Date exitDateTime = parseDateTime(exitDateStr, exitTimeStr, exitAmPmStr);
         
             long entryTimestamp = entryDateTime.getTime();
             long exitTimestamp = exitDateTime.getTime();
             long timeDifferenceMillis = exitTimestamp - entryTimestamp;
             long hours = TimeUnit.MILLISECONDS.toHours(timeDifferenceMillis);
             long days = TimeUnit.MILLISECONDS.toDays(timeDifferenceMillis);
             
               int hourlyFee = (int) hours * hourly;
              int dailyFee = (int) days * daily;
              int extraHours = (int) (hours - days * 24);
            int extraHourlyFee = (int) extraHours * hourly;

        int totalFee = 0;
        if (days > 0) {
            // add daily fee plus any extra hourly fee
            totalFee = dailyFee + extraHourlyFee;
        } else {
            // add hourly fee plus any extra hourly fee
            totalFee = hourlyFee ;
        }
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/parking","root","");
            String sql="INSERT into car(owner2, contact2, vehicle_no2, entry_date2, entry_time2, exit_date2, exit_time2, fee2) Values(?,?,?,?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,name );
            pst.setString(2, contact);
            pst.setString(3, vehicle);
            pst.setDate(4, new java.sql.Date(parseDateTime(entryDateStr, entryTimeStr, entryAmPmStr).getTime()));
            pst.setTime(5,new java.sql.Time(date_time((int)hr1.getValue(), (int)min1.getValue(),(String) entryAmPmStr).getTime()));
            pst.setDate(6, new java.sql.Date(parseDateTime(exitDateStr, exitTimeStr, exitAmPmStr).getTime()));
            pst.setTime(7, new java.sql.Time(date_time((int)hr2.getValue(), (int)min2.getValue(),(String) exitAmPmStr).getTime()));
            pst.setInt(8, totalFee);
            pst.executeUpdate();
            owner.setText("");
            phnno.setText("");
            vehicleno.setText("");
            entrydate1.setText("");
            hr1.setValue(0);
            min1.setValue(0);
            am1.setSelectedIndex(-1);
            exitdate1.setText("");
            hr2.setValue(0);
            min2.setValue(0);
            am2.setSelectedIndex(-1); 
            
             JOptionPane.showMessageDialog(this,"The total fee you have to pay is: "+ totalFee);
             // TODO add your handling code here:
         } catch (ParseException ex) {
             Logger.getLogger(Car.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(Car.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(Car.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_calActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Car().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox am1;
    private javax.swing.JComboBox am2;
    private javax.swing.JPanel beigep;
    private javax.swing.JPanel brownp;
    private javax.swing.JButton cal;
    private javax.swing.JLabel contact;
    private javax.swing.JTextField entrydate1;
    private javax.swing.JLabel entrydatelbl;
    private javax.swing.JLabel entrylbl;
    private javax.swing.JTextField exitdate1;
    private javax.swing.JLabel exitdatelbl;
    private javax.swing.JLabel exitlbl;
    private javax.swing.JLabel home;
    private javax.swing.JSpinner hr1;
    private javax.swing.JSpinner hr2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menu1;
    private javax.swing.JLabel menu2;
    private javax.swing.JSpinner min1;
    private javax.swing.JSpinner min2;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField owner;
    private javax.swing.JLabel phlbl;
    private javax.swing.JTextField phnno;
    private javax.swing.JLabel records;
    private javax.swing.JTextField vehicleno;
    private javax.swing.JLabel vnolbl;
    // End of variables declaration//GEN-END:variables
}
