/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Parking_lot;

/**
 *
 * @author HARPREET
 */
public class Bike extends javax.swing.JFrame {
     int x=200;
     int y=600;
     
    /**
     * Creates new form Bike
     */
    public Bike() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        beigep = new javax.swing.JPanel();
        menu1 = new javax.swing.JLabel();
        brownp = new javax.swing.JPanel();
        menu2 = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        records = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        phlbl = new javax.swing.JLabel();
        vnolbl = new javax.swing.JLabel();
        entrylbl = new javax.swing.JLabel();
        exitlbl = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        phnno = new javax.swing.JTextField();
        vehicleno = new javax.swing.JTextField();
        hr1 = new javax.swing.JSpinner();
        min1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jcb1 = new javax.swing.JComboBox();
        hr2 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        min2 = new javax.swing.JSpinner();
        jcb2 = new javax.swing.JComboBox();
        entrydatelbl = new javax.swing.JLabel();
        entrydate1 = new javax.swing.JTextField();
        exitdatelbl = new javax.swing.JLabel();
        exitdate1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 211, 163));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel1.setFont(new java.awt.Font("Niagara Engraved", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 0));
        jLabel1.setText("       2-WHEELER");

        jLayeredPane2.setBackground(new java.awt.Color(255, 255, 255));

        beigep.setBackground(new java.awt.Color(255, 211, 163));

        menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Parking_lot/menu.png"))); // NOI18N
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout beigepLayout = new javax.swing.GroupLayout(beigep);
        beigep.setLayout(beigepLayout);
        beigepLayout.setHorizontalGroup(
            beigepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beigepLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        beigepLayout.setVerticalGroup(
            beigepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(beigepLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        brownp.setBackground(new java.awt.Color(153, 102, 0));

        menu2.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        menu2.setForeground(new java.awt.Color(255, 211, 163));
        menu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu2.setText("YOUR PARKING");
        menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu2MouseClicked(evt);
            }
        });

        home.setFont(new java.awt.Font("Segoe UI Light", 1, 15)); // NOI18N
        home.setForeground(new java.awt.Color(255, 211, 163));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("HOME");
        home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 211, 163), 2, true));

        records.setFont(new java.awt.Font("Segoe UI Light", 1, 15)); // NOI18N
        records.setForeground(new java.awt.Color(255, 211, 163));
        records.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        records.setText("RECORDS");
        records.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 211, 163), 2, true));

        logout.setFont(new java.awt.Font("Segoe UI Light", 1, 15)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 211, 163));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("LOG OUT");
        logout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 211, 163), 2, true));

        contact.setFont(new java.awt.Font("Segoe UI Light", 1, 15)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 211, 163));
        contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contact.setText("CONTACT US");
        contact.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 211, 163), 2, true));

        javax.swing.GroupLayout brownpLayout = new javax.swing.GroupLayout(brownp);
        brownp.setLayout(brownpLayout);
        brownpLayout.setHorizontalGroup(
            brownpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brownpLayout.createSequentialGroup()
                .addGroup(brownpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(brownpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(brownpLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(brownpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(records, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(home, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addContainerGap())
        );
        brownpLayout.setVerticalGroup(
            brownpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(brownpLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(records, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(beigep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(brownp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(beigep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(brownp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane2.setLayer(beigep, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(brownp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        namelbl.setBackground(new java.awt.Color(255, 255, 255));
        namelbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        namelbl.setForeground(new java.awt.Color(153, 102, 0));
        namelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namelbl.setText("OWNER'S NAME");
        namelbl.setPreferredSize(new java.awt.Dimension(200, 30));

        phlbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        phlbl.setForeground(new java.awt.Color(153, 102, 0));
        phlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phlbl.setText("OWNER'S CONTACT NO.");
        phlbl.setPreferredSize(new java.awt.Dimension(200, 30));

        vnolbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        vnolbl.setForeground(new java.awt.Color(153, 102, 0));
        vnolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vnolbl.setText("VEHICLE NO.");
        vnolbl.setPreferredSize(new java.awt.Dimension(200, 30));

        entrylbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        entrylbl.setForeground(new java.awt.Color(153, 102, 0));
        entrylbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrylbl.setText("ENTRY TIME");

        exitlbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        exitlbl.setForeground(new java.awt.Color(153, 102, 0));
        exitlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitlbl.setText("EXIT TIME");
        exitlbl.setPreferredSize(new java.awt.Dimension(200, 30));

        name.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(153, 102, 0));
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 102, 0), 2, true));
        name.setPreferredSize(new java.awt.Dimension(200, 30));

        phnno.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        phnno.setForeground(new java.awt.Color(153, 102, 0));
        phnno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phnno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 102, 0), 2, true));
        phnno.setPreferredSize(new java.awt.Dimension(200, 30));

        vehicleno.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        vehicleno.setForeground(new java.awt.Color(153, 102, 0));
        vehicleno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vehicleno.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 102, 0), 2, true));
        vehicleno.setPreferredSize(new java.awt.Dimension(200, 30));

        hr1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));
        hr1.setPreferredSize(new java.awt.Dimension(40, 30));

        min1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        min1.setPreferredSize(new java.awt.Dimension(40, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(":");

        jcb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "PM" }));
        jcb1.setPreferredSize(new java.awt.Dimension(50, 30));

        hr2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));
        hr2.setPreferredSize(new java.awt.Dimension(40, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(":");

        min2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        min2.setPreferredSize(new java.awt.Dimension(40, 30));

        jcb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "PM" }));
        jcb2.setPreferredSize(new java.awt.Dimension(50, 30));

        entrydatelbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        entrydatelbl.setForeground(new java.awt.Color(153, 102, 0));
        entrydatelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrydatelbl.setText("ENTRY DATE");
        entrydatelbl.setPreferredSize(new java.awt.Dimension(200, 30));

        entrydate1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        entrydate1.setForeground(new java.awt.Color(153, 102, 0));
        entrydate1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entrydate1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 102, 0), 2, true));
        entrydate1.setPreferredSize(new java.awt.Dimension(200, 30));

        exitdatelbl.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        exitdatelbl.setForeground(new java.awt.Color(153, 102, 0));
        exitdatelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitdatelbl.setText("EXIT DATE");
        exitdatelbl.setPreferredSize(new java.awt.Dimension(200, 30));

        exitdate1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        exitdate1.setForeground(new java.awt.Color(153, 102, 0));
        exitdate1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        exitdate1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 102, 0), 2, true));
        exitdate1.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 75, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(phlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(entrylbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(exitlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitdatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vnolbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entrydatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entrydate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehicleno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hr1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(min1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcb1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hr2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(min2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcb2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(exitdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phlbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vnolbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entrydatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entrydate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entrylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hr1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(min1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jcb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitdatelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hr2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(min2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 120, Short.MAX_VALUE))
            .addComponent(jLayeredPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseClicked
        if(x==200){
            beigep.setSize(x,y);
            Thread t= new Thread(){
               @Override
               public void run(){
                   try{
                      for(int i=200;i>=0;i--){
                          Thread.sleep(1);
                          beigep.setSize(i,y);
                      } 
                   }
                   catch(Exception e){
                       e.printStackTrace();
                   }
               }
            };t.start();
            x=0;
        }
// TODO add your handling code here:
    }//GEN-LAST:event_menu1MouseClicked

    private void menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2MouseClicked
        
        if(x==0){
            beigep.show();
            beigep.setSize(x,y);
            Thread t=new Thread(){
                @Override
                public void run(){
                    try{
                       for(int i=0;i<=x;i++){
                          Thread.sleep(1);
                          beigep.setSize(i,y); 
                       }
                    }
                    catch(Exception e){
                        e.printStackTrace();
                    }
                }
            };t.start();
            x=200;
        }
// TODO add your handling code here:
    }//GEN-LAST:event_menu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bike.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bike().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel beigep;
    private javax.swing.JPanel brownp;
    private javax.swing.JLabel contact;
    private javax.swing.JTextField entrydate1;
    private javax.swing.JLabel entrydatelbl;
    private javax.swing.JLabel entrylbl;
    private javax.swing.JTextField exitdate1;
    private javax.swing.JLabel exitdatelbl;
    private javax.swing.JLabel exitlbl;
    private javax.swing.JLabel home;
    private javax.swing.JSpinner hr1;
    private javax.swing.JSpinner hr2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcb1;
    private javax.swing.JComboBox jcb2;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menu1;
    private javax.swing.JLabel menu2;
    private javax.swing.JSpinner min1;
    private javax.swing.JSpinner min2;
    private javax.swing.JTextField name;
    private javax.swing.JLabel namelbl;
    private javax.swing.JLabel phlbl;
    private javax.swing.JTextField phnno;
    private javax.swing.JLabel records;
    private javax.swing.JTextField vehicleno;
    private javax.swing.JLabel vnolbl;
    // End of variables declaration//GEN-END:variables
}
